# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c873b38b4a4fe02136045b152ecad6dd5e3ff2ff181a6cd6c1bb9c991438ed9d0af1edb89ab82503c9acee4093e32fa7567430b445153b08f46a9242227f4ae

test:
  secret_key_base: 4d50fe2bd5e2c7e38bb2f5b55d0d9806ae2f26d7d125ec902c2c2318c439ca3d3b54c86b0200babdcd967ca8b99f761edd080fb6aae60ca6fa7f52afa5eb2c2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
