# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd1df48f4249aadfc0dc6d41fee02f808edb8a24675fb11acf76228b4265b6d1fba71011afdac624c475606453f0fefdab6fd98e4ee7daaad4d3fb6f6871dc51

test:
  secret_key_base: 6f7b7e88c309476b89cdda5581299928a9a4644fee328489b236365e5fd8416b6bf0d71e4510b12c37477be6d89e3b19d7603e1375bc4a2048784330964a25b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
